title: "Blog: Machine Learning Equations by Saurabh Verma"
author: "Saurabh Verma"
description: "Blog: Machine Learning Equations by Saurabh Verma"
#subheading: "Really cool blog about ... something"
more: "read more"
url: "http://www-users.cs.umn.edu/~verma/"
#baseurl: "/contrast" # comment out if in root directory

comments:
    disqus: "saurabhML"
#    isso: "comments.mysite.org"

style:
#    body: "whitesmoke"
    padding: 33%
    anchor: "#46f"
    serif-heading: true
    nav: "#181818"
#    headline: "#06f"
    description: "white"
    article:
        odd: "#ffffff"
        even: "#222222"

links:
  - github: "https://github.com/vermaMachineLearning/"
  - linkedin: "https://www.linkedin.com/in/saurabh-verma-10076544"
  - facebook: "https://www.facebook.com/saurabh.verma.355"

paginate: 10
excerpt_separator: "\n\n\n" # excerpt ends after two blank lines
defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]
gems: [jekyll-feed,jekyll-paginate] # include feed plugin (supported by gh-pages)
markdown: kramdown
# Google services
google_analytics: UA-78615814-1
